FROM php:8.1-fpm

# Extensions php nécessaires pour Laravel
RUN apt-get update && apt-get install -y git unzip zip libpng-dev libonig-dev libxml2-dev curl nodejs npm \
  && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Dossier de travail
WORKDIR /var/www/html

#Copier le projet dans le conteneur
COPY . /var/www/html/

# Dépendences PHP + Node
RUN composer install --no-interaction --prefer-dist --optimize-autoloader \
  && npm install \
  && npm run build 

# Permissions Laravel
RUN chown -R www-data:www-data /var/www/html \
  && chmod -R 775 /var/www/html/storage \
  && chmod -R 775 /var/www/html/bootstrap/cache

# Entry point pour lancer artisan
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]